services:
  # Backend API Service
  - type: web
    name: trainingpulse-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    region: oregon
    buildFilter:
      paths:
      - backend/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_VERSION
        value: v1
      - key: PORT
        value: 3001
      # Aiven Database URL - Set this in Render Dashboard
      - key: DATABASE_URL
        sync: false
      # Skip Redis if not needed
      - key: SKIP_REDIS
        value: true
      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      # CORS - will be updated with frontend URL after deployment
      - key: CORS_ORIGIN
        sync: false
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: BULK_RATE_LIMIT_MAX_REQUESTS
        value: 10
      # Logging
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_REQUEST_LOGGING
        value: true
      # Email (optional)
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: noreply@trainingpulse.com
      - key: FROM_NAME
        value: TrainingPulse
      # File Upload (optional)
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        value: trainingpulse-uploads
      # Teams Integration (optional)
      - key: TEAMS_WEBHOOK_URL
        sync: false
      # SSL Configuration for Aiven
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: 0

  # Frontend Service
  - type: web
    name: trainingpulse
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    plan: free
    buildFilter:
      paths:
      - frontend/**
    envVars:
      # API URL - will be set after backend deployment
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_API_VERSION
        value: v1
      - key: VITE_APP_NAME
        value: TrainingPulse
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_ENABLE_ANALYTICS
        value: true
      - key: VITE_ENABLE_NOTIFICATIONS
        value: true
      - key: VITE_ENABLE_BULK_OPERATIONS
        value: true
      # File Upload Configuration
      - key: VITE_MAX_FILE_SIZE
        value: 10485760
      - key: VITE_ALLOWED_FILE_TYPES
        value: pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: camera=(), microphone=(), geolocation=()
    routes:
      - type: rewrite
        source: /*
        destination: /index.html